name: Tableau Workbook Production Workflows
on:
  pull_request:
      branches:
        - master
      types: [closed]
      paths:
        - 'tableau_workbook/**'
jobs:
  tableau-production-deployments:
    name: Tableau Workbook Production Deployments
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: 'Tableau Workbook Deployments Action'
        uses: ./action/tableau-workbook-action
        env:
          USERNAME: ${{ secrets.TABLEAU_DEPLOYMENT_USERNAME }}
          PASSWORD: ${{ secrets.TABLEAU_DEPLOYMENT_PASSWORD }}
          SITE_ID: ${{ secrets.TABLEAU_DEPLOYMENT_SITE_ID }}
          TABLEAU_URL: ${{ secrets.TABLEAU_DEPLOYMENT_TABLEAU_URL }}
        with:
          workbook_dir: tableau_workbook/workbooks
          env: production
          repo_token: ${{ secrets.GITHUB_TOKEN }}
