name: Tableau Workbook Production Workflows - Cloud
on:
  pull_request:
      branches:
        - master
      types: [closed]
      paths:
        - 'tableau/workbooks/cloud/**'
jobs:
  tableau-production-deployments:
    name: Tableau Workbook Production Deployments to Cloud
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: 'Tableau Workbook Deployments Action'
        uses: ./
        env:
          USERNAME_CLOUD:  ${{ secrets.USERNAME_CLOUD }}
          PASSWORD_CLOUD: ${{ secrets.PASSWORD_CLOUD }}
          SITE_ID_CLOUD: ${{ secrets.SITE_ID_CLOUD }}
          TABLEAU_URL_CLOUD: ${{ secrets.TABLEAU_URL_CLOUD }}
          PAT_NAME: ${{ secrets.PAT_NAME_CLOUD }}
          PAT: ${{ secrets.PAT_CLOUD }}
          SITE_NAME: ${{ secrets.SITE_NAME_CLOUD }}
        with:
          workbook_dir: tableau/workbooks/cloud
          env: production
          tableau_type: cloud
          repo_token: ${{ secrets.GITHUB_TOKEN }}
