name: Tableau Workbook Production Workflows - Server Internal (Kagebunshin)
on:
  pull_request:
      branches:
        - master
      types: [closed]
      paths:
        - 'tests/workbooks/internal(kagebunshin)/**'
jobs:
  tableau-production-deployments:
    name: Tableau Workbook Production Deployments
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: 'Tableau Workbook Deployments Action'
        uses: ./
        env:
          USERNAME:  ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SITE_ID: ${{ secrets.SITE_ID }}
          TABLEAU_URL: ${{ secrets.TABLEAU_URL }}
        with:
          workbook_dir: tests/workbooks/internal(kagebunshin)
          env: production
          repo_token: ${{ secrets.GITHUB_TOKEN }}
